---
title: "Supplementary Materials for Sun et al. 2022"
author: "Sun; Wang; Wen; Chuan-Peng"
date: '2022-10-30'
output: html_notebook
---

# Inter-rater reliability
Below are the code for calculating the inter-rater reliability:

```{r IRR}
library(tidyverse)

results <- read.csv("Interrater_reliability_Raw.csv")
ratings <- dplyr::select(results, R1, R2, R3, R4, R5, R6, R7, R8, R9, R10, R11, R12, R13, R14, R15, R16, R17, R18, R19, R20, R21, R22, R23, R24, R25, R26, R27, R28, R29, R30, R31, R32, R33, R34, R35, R36, R37, R38, R39, R40, R41, R42, R43, R44, R45, R46, R47, R48, R49, R50, R51, R52, R53, R54, R55, R56, R57, R58, R59, R60, R61, R62, R63, R64, R65, R66, R67, R68, R69, R70, R71, R72, R73, R74, R75, R76) 

ratings2 <- ratings %>% filter(row_number()>6)

rater1 <- ratings2[,seq(1,ncol(ratings2),2)]
rater2 <- ratings2[,seq(0,ncol(ratings2),2)]

# install.packages("xml2")
library(xml2)
raterlist1 <- as.data.frame(rater1)
raterlist2 <- as.data.frame(rater2)

raterlisted1 <- c(raterlist1[,1])

for(i in 2:38){
  raterlisted1 <- c(raterlisted1,raterlist1[,i])
}

raterlisted2 <- c(raterlist2[,1])
for(i in 2:38){
  raterlisted2 <- c(raterlisted2,raterlist2[,i])
}

r1 <- as.numeric (raterlisted1)
r2 <- as.numeric(raterlisted2) 


dat <- tibble(
  rater1 = r1,
  rater2 = r2
) %>%
  dplyr::filter(!is.na(rater1) & !is.na(rater2))

# install.packages("irrCAC")
library(irrCAC)
gwet.ac1.raw(dat)

```

# Plot figure 4

Below is the code for plotting figure 4.

```{r figure4}
library(tidyverse)
#install.packages("easyalluvial")
#install.packages("parcats")
library(parcats)
library(easyalluvial)

dat1 <- read.csv("Figure4_data.csv") %>%
  dplyr::mutate_if(is.character,as.factor) %>%
  dplyr::select(-c(Freq, First_Author,Article_ID, Participant, Task,Control_conditions)) %>%
  dplyr::mutate(Contrast = factor(Contrast, 
  levels = c("close", "celebrity", "stranger", "NP", "multi")))%>%
  dplyr::rename(`Task: Phase 1` =  Phase_1,
                `Task: Phase 2` =  Phase_2,
               `Control_conditions`= Contrast) 

# using the last column to color the flow
p_selfref <- dat1 %>%
  easyalluvial::alluvial_wide(.,
                              fill_by = "last_variable",
                              #col_vector_flow = 'grey',
                              #col_vector_value = palette_filter( greys = F),
                              stratum_label_size = 1, 
                              stratum_width = 1/3,
                              # col_vector_value = RColorBrewer::brewer.pal(9, "Paired")[c(4, 7, 5, 8, 6)],
                              colorful_fill_variable_stratum = T) 
parcats::parcats(p_selfref, marginal_histograms = FALSE, imp = TRUE, data_input = dat1, arrangement = 'freeform',
                 labelfont = list(size = 18, color = "black", family = "Times New Roman"),
                 offset_imp = 1)
```

System information for running this script:
```
R version 4.2.0 (2022-04-22)
Platform: aarch64-apple-darwin20 (64-bit)
Running under: macOS Monterey 12.6

Matrix products: default
LAPACK: /Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] easyalluvial_0.3.1 parcats_0.0.4      irrCAC_1.0         xml2_1.3.3         forcats_0.5.2     
 [6] stringr_1.4.1      dplyr_1.0.10       purrr_0.3.5        readr_2.1.3        tidyr_1.2.1       
[11] tibble_3.1.8       ggplot2_3.3.6      tidyverse_1.3.2   
```
